###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "Dennis Fuentes",
    "sexo": true,
    "edad": 24,
    "correo": "Denn@gmail.com",
    "telefono": "1234-5678",
    "estado": true,
}

// Leer Usuarios
###
GET http://localhost:9000/api/users HTTP/1.1\

###

//Leer un usuario
GET http://localhost:9000/api/users/627432b85dc091fececa7049 HTTP/1.1

//actualizar usuario
###
PUT http://localhost:9000/api/users/62706fcc7c576a74bbd8e7f6 HTTP/1.1
Content-Type: application/json

{
   "nombre": "Dennis Landaverde",
    "edad": 24,
    "correo": "Den@gmail.com",
    "telefono": "1234-5678",
    "estado": true
}

//Eliminar usuario
###
DELETE http://localhost:9000/api/users/627432b85dc091fececa7049 HTTP/1.1