###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "Juan",
    "sexo": true,
    "edad": 31,
    "correo": "juan@gmail.com",
    "telefono": "1234-5678",
    "estado": true,
    "VuM": false
}

// Leer Usuarios
###
GET http://localhost:9000/api/users HTTP/1.1

###

//Leer un usuario
GET http://localhost:9000/api/users/627c667848daba3594861d63 HTTP/1.1

//actualizar usuario
###
PUT http://localhost:9000/api/users/627c667848daba3594861d63 HTTP/1.1
Content-Type: application/json

{

    "correo": "landa@gmail.com"

}

//Eliminar usuario
###
DELETE http://localhost:9000/api/users/627c667848daba3594861d63 HTTP/1.1



###
//Reguistro loguin
POST http://localhost:9000/api/registro HTTP/1.1
Content-Type: application/json

{
    "usuario":"elmer",
    "pass":"123456789",
    "adminn":"Elmer",
    "admina": "Ponce",
    "admine": 21,
    "admins": true
}

###
//login
POST http://localhost:9000/api/login HTTP/1.1
Content-Type: application/json

{
    "usuario":"dennisl10",
    "pass":"12345"

}
