###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "Juan Landaverde",
    "sexo": true,
    "edad": 31,
    "correo": "juan@gmail.com",
    "telefono": "1234-5678",
    "estado": true
}

// Leer Usuarios
###
GET http://localhost:9000/api/users HTTP/1.1\

###

//Leer un usuario
GET http://localhost:9000/api/users/627c667848daba3594861d63 HTTP/1.1

//actualizar usuario
###
PUT http://localhost:9000/api/users/627c667848daba3594861d63 HTTP/1.1
Content-Type: application/json

{

    "correo": "landa@gmail.com"

}

//Eliminar usuario
###
DELETE http://localhost:9000/api/users/627c667848daba3594861d63 HTTP/1.1